### PR TITLE
Add proxy methods for ACL

### PR DESCRIPTION
**Pull request by jamiehannaford**

### CODE REVIEW

**Comment by jamiehannaford** [comment]
Whenever I test this IRL I get this error @briancurtin:

```
>>> d.get_acls_for_ha_instance(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jamie/.venvs/k8s-rd/lib/python2.7/site-packages/rackspace/database/v1/_proxy.py", line 376, in get_acls_for_ha_instance
    return instance.get_acls(self.session)
  File "/Users/jamie/.venvs/k8s-rd/lib/python2.7/site-packages/rackspace/database/v1/high_availability_instance.py", line 96, in get_acls
    resp = session.get(url, service=self.service).body
  File "/Users/jamie/.venvs/k8s-rd/lib/python2.7/site-packages/keystoneauth1/session.py", line 667, in get
    return self.request(url, 'GET', **kwargs)
  File "/Users/jamie/.venvs/k8s-rd/lib/python2.7/site-packages/openstack/session.py", line 66, in map_exceptions_wrapper
    raise exceptions.SDKException(message=e.message, cause=e)
openstack.exceptions.SDKException: Could not find requested endpoint in Service Catalog.
```

But it works for other methods:

```
>>> d.backups()
<generator object list at 0x10de8dfa0>
```

**Comment by briancurtin** [comment]
Yeah there's something broken to where the ServiceFilter for the extension doesn't know what version the Cloud Databases package is, so when the session goes to figure out the endpoint it doesn't know how to compare what we have in the library to what's available from the actual REST API. I'm working on other Cloud Databases stuff and trying to get that piece to work right now.

**Comment by briancurtin** [comment]
Sorry for the delay, been trying to figure a bunch of other similar things out, but yeah this has to do with how we actually have two separate ServiceFilter instances that need to be merged. We have the upstream "database" entry that knows it's a v1 (which is why other things work, since they can find a v1 endpoint), but we also have the "rax:database" entry which is not fully setup and doesn't have a version specified. There needs to just be one, and it needs a version. Working on that now.

**Comment by jamiehannaford** [comment]
I'm gonna go ahead and close this PR because I don't have much time to finish it.

**Pull request closed without merging**
